import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { inspectLegacyArtifacts, migrateLegacyData } from "../src/installation-migration";
import { updateJournal } from "../src/update-journal";
import { createHash } from "node:crypto";
test("migration copies missing data, preserves conflicts and retains unknown directories", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kc-migration-")), data = path.join(root, "data"), legacy = path.join(root, "UserData");
  await mkdir(legacy); await writeFile(path.join(legacy, "settings.json"), JSON.stringify({ instancePath: "original" }));
  await writeFile(path.join(legacy, "preserved-report.txt"), "Do not delete my records");
  migrateLegacyData(data, legacy, () => undefined);
  assert.equal(await readFile(path.join(data, "legacy-user-data-backup/preserved-report.txt"), "utf8"), "Do not delete my records");
  assert.equal(await readFile(path.join(data, "settings.json"), "utf8"), await readFile(path.join(legacy, "settings.json"), "utf8"));
  await writeFile(path.join(data, "settings.json"), JSON.stringify({ instancePath: "current" }));
  migrateLegacyData(data, legacy, () => undefined); assert.match(await readFile(path.join(data, "settings.json"), "utf8"), /current/);
  const known = path.join(root, "app-0.3.1"), unknown = path.join(root, "app-0.2.0");
  await mkdir(path.join(known, "resources/app"), { recursive: true }); await mkdir(unknown);
  await writeFile(path.join(known, "resources/app/package.json"), JSON.stringify({ name: "kingdom-chronicle-desktop", version: "0.3.1" }));
  await writeFile(path.join(known, "electron-runtime.bin"), "owned runtime");
  await writeFile(path.join(known, "KingdomChronicle.exe"), "verified launcher");
  await writeFile(path.join(root, "KingdomChronicle.exe"), "verified launcher");
  await mkdir(path.join(root, "packages"));
  const packageBytes = Buffer.from("owned package"), packageName = "KingdomChronicle-0.3.1-full.nupkg";
  await writeFile(path.join(root, "packages", packageName), packageBytes);
  await writeFile(path.join(root, "packages/RELEASES"), `${createHash("sha1").update(packageBytes).digest("hex")} ${packageName} ${packageBytes.length}`);
  await writeFile(path.join(root, "packages/unknown.txt"), "retain");
  inspectLegacyArtifacts(root, data, true, () => undefined);
  assert.equal(existsSync(known), false); assert.equal(existsSync(unknown), true); assert.equal(existsSync(legacy), true);
  assert.equal(existsSync(path.join(root, "KingdomChronicle.exe")), false);
  assert.equal(existsSync(path.join(root, "packages", packageName)), false);
  assert.equal(existsSync(path.join(root, "packages/unknown.txt")), true);
});
test("restart journal proves expected version or records a durable failure", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "kc-journal-")), journal = updateJournal(root);
  journal.begin("0.3.2", "0.3.3"); assert.throws(() => journal.health("0.3.2", () => undefined), /Expected/);
  assert.match(await readFile(path.join(root, "updates/restart.json"), "utf8"), /failed/);
  assert.equal(journal.health("0.3.3", () => undefined), true);
  const success = JSON.parse(await readFile(path.join(root, "updates/last-success.json"), "utf8"));
  assert.equal(success.status, "complete"); assert.equal(success.currentVersion, "0.3.3");
  assert.equal(success.detail, undefined); assert.equal(existsSync(path.join(root, "updates/restart.json")), false);
  assert.match(await readFile(path.join(root, "logs/updater.log"), "utf8"), /Previous version: 0.3.2. Current version: 0.3.3/);
});
